language: node_js
node_js:
 - 14

install:
 - npm install istanbul
 - npm install nyc
 - npm install coveralls

script:
  - npm run coverage
  
after_script:
  - npm run coveralls

notifications:
 email: false
